import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <footer className="border-t border-[var(--border)] bg-[var(--bg-primary)] px-6 py-6">
          <nav className="mx-auto flex w-full max-w-6xl flex-col gap-3 text-xs font-bold text-[var(--text-secondary)] sm:flex-row sm:items-center sm:justify-center sm:gap-6">
            <a
              href="https://t.me/monoai_automation"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[var(--accent)]"
            >
              Telegram channel
            </a>
            <a
              href="https://ai-automation.expert"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[var(--accent)]"
            >
              ai-automation.expert
            </a>
            <a
              href="https://t.me/monoai_automation_bot"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-[var(--accent)]"
            >
              @monoai_automation_bot
            </a>
          </nav>
        </footer>
      </body>
    </html>
  );
}
